language: node_js
node_js: stable

install:
  - npm install

script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "sinoreimu"
  - git config user.email "su@geekzh.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - blog-source
